name             'aws-custom'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures aws-custom'
long_description 'Installs/Configures aws-custom'
version          '0.1.0'

depends 'aws', '= 2.5.0'
provides 'aws-tag::ec2'
