name             'testapp'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures testapp'
long_description 'Installs/Configures testapp'
version          '0.1.0'
depends 'git', '~> 4.1.0'
